<?php require VIEWS_PATH . 'includes/header.phtml';?>
<div class="container">

    <div class="jumbotron">
        <h1>Bem Vindo ao Projeto Um</h1>
        <p>
            Projeto PHP Orientado a Objetos
        </p>
        <p>
            <a class="btn btn-lg btn-primary" href="" role="button">Saiba mais &raquo;</a>
        </p>
    </div>

    <div class="col-md-12">
        <?php foreach($this->products as $product):?>
        <div class="col-md-4">
            <img src="http://via.placeholder.com/350x150?text=<?=$product['name'];?>" alt="" class="img-responsive">
            <h2><a href="<?=HOME;?>/product/<?=$product['id'];?>"><?=$product['name'];?></a></h2>
            <p><?=$product['description'];?></p>
            <p>R$ <?=number_format($product['price'], 2, ',', '.');?></p>
        </div>
        <?php endforeach;?>
    </div>

</div>
<?php require VIEWS_PATH . 'includes/footer.phtml';?>
